### PR TITLE
Watchdog for buildinfo.json

### PR DESCRIPTION
**Pull request by StopMotionCuber**
This adds an additional watchdog that writes the `buildinfo.json` file.

It assumes to be executed in a setup Repository with push permission and origin set and is expected to be used and merged with https://github.com/factoriotools/factorio-docker/pull/382/

### CODE REVIEW

**Comment by fank** [comment]
Sorry but this will not work, the watchdog is running in a container, and needs to be intigrated in the current golang process.

**Comment by StopMotionCuber** [comment]
> Sorry but this will not work, the watchdog is running in a container, and needs to be intigrated in the current golang process.

I see, I was not really aware of the Dockerfile deployment. Would adapting the Dockerfile and integrate GitHub tokens into the watchdog be an option? I'm not planning on adapting that Discord feature. I think that is not really needed as we can just subscribe to the official Factorio Server anmouncements

**Comment by fank** [comment]
I did the changes in https://github.com/factoriotools/factorio-docker-watchdog/pull/10 for go, i am not the fan of mixing multiple languages in the same repo.

**Comment by StopMotionCuber** [comment]
Ah, OK, didn't see that. Closing this in favor of #10 then

**Comment by SuperSandro2000** [comment]
> Sorry but this will not work, the watchdog is running in a container, and needs to be intigrated in the current golang process.

Golang is just not a good language choice for such a simple updater script.

**Pull request closed without merging**
